-- MySQL Script generated by MySQL Workbench
-- Wed 02 Dec 2015 09:54:56 PM PHT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ThesisDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ThesisDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ThesisDB` DEFAULT CHARACTER SET utf8 ;
USE `ThesisDB` ;

-- -----------------------------------------------------
-- Table `ThesisDB`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`rooms` (
  `rooms_id` INT NOT NULL AUTO_INCREMENT,
  `rooms_name` VARCHAR(45) NOT NULL,
  `rooms_address` INT NULL,
  `rooms_port` INT NULL,
  `rooms_status` INT NOT NULL,
  PRIMARY KEY (`rooms_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`floors` (
  `floors_id` INT NOT NULL AUTO_INCREMENT,
  `floors_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`floors_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`floor_room_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`floor_room_groups` (
  `floor_room_groups_id` INT NOT NULL AUTO_INCREMENT,
  `floors_id` INT NOT NULL,
  `rooms_id` INT NOT NULL,
  PRIMARY KEY (`floor_room_groups_id`),
  INDEX `fk_floor_room_group_floors1_idx` (`floors_id` ASC),
  INDEX `fk_floor_room_group_rooms1_idx` (`rooms_id` ASC),
  CONSTRAINT `fk_floor_room_group_floors1`
    FOREIGN KEY (`floors_id`)
    REFERENCES `ThesisDB`.`floors` (`floors_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floor_room_group_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `ThesisDB`.`rooms` (`rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`room_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`room_schedules` (
  `room_schedules_id` INT NOT NULL AUTO_INCREMENT,
  `rooms_id` INT NOT NULL,
  `room_schedules_day` VARCHAR(45) NULL,
  `room_schedules_date` DATE NULL,
  `room_schedules_time` INT NULL,
  PRIMARY KEY (`room_schedules_id`),
  INDEX `fk_room_schedule_rooms1_idx` (`rooms_id` ASC),
  CONSTRAINT `fk_room_schedule_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `ThesisDB`.`rooms` (`rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`user_details` (
  `user_details_id` INT NOT NULL AUTO_INCREMENT,
  `user_details_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_details_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`room_consumptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`room_consumptions` (
  `room_consumptions_id` INT NOT NULL AUTO_INCREMENT,
  `rooms_id` INT NOT NULL,
  `room_consumptions` DOUBLE NOT NULL,
  PRIMARY KEY (`room_consumptions_id`),
  INDEX `fk_room_consumption_rooms1_idx` (`rooms_id` ASC),
  CONSTRAINT `fk_room_consumption_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `ThesisDB`.`rooms` (`rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`room_devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`room_devices` (
  `room_devices_id` INT NOT NULL AUTO_INCREMENT,
  `rooms_id` INT NOT NULL,
  `room_devices_name` VARCHAR(45) NOT NULL,
  `room_devices_port` INT NULL,
  `room_devices_status` INT NOT NULL,
  PRIMARY KEY (`room_devices_id`),
  INDEX `fk_room_devices_rooms1_idx` (`rooms_id` ASC),
  CONSTRAINT `fk_room_devices_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `ThesisDB`.`rooms` (`rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThesisDB`.`room_device_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThesisDB`.`room_device_schedules` (
  `room_device_schedules_id` INT NOT NULL AUTO_INCREMENT,
  `room_devices_id` INT NOT NULL,
  `room_schedules_id` INT NOT NULL,
  PRIMARY KEY (`room_device_schedules_id`),
  INDEX `fk_room_device_schedules_room_devices1_idx` (`room_devices_id` ASC),
  INDEX `fk_room_device_schedules_room_schedules1_idx` (`room_schedules_id` ASC),
  CONSTRAINT `fk_room_device_schedules_room_devices1`
    FOREIGN KEY (`room_devices_id`)
    REFERENCES `ThesisDB`.`room_devices` (`room_devices_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_device_schedules_room_schedules1`
    FOREIGN KEY (`room_schedules_id`)
    REFERENCES `ThesisDB`.`room_schedules` (`room_schedules_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
